### ISSUE TITLE
preview/export creates dump

### ISSUE THREAD

**Issue by riccardoklinger** [volaya/qgis-ol3#2]
When trying do do a preview or export I received the error at the end. I was having three layers and all the layers have EPSG:4326.  

Traceback (most recent call last):
  File "C:\Users\rikl/.qgis2/python/plugins\qgis-ol3-master\maindialog.py", line 93, in update
    writeOL(layers, groups, popup, visible, params, utils.tempFolder())
  File "C:\Users\rikl/.qgis2/python/plugins\qgis-ol3-master\olwriter.py", line 45, in writeOL
    mapbounds = bounds(settings["Scale/Zoom"]["Extent"] == "Canvas extent", layers)
  File "C:\Users\rikl/.qgis2/python/plugins\qgis-ol3-master\olwriter.py", line 115, in bounds
    extent = transform.transform(canvas.extent())
QgsCsException: Vorwärtstransformation von
(-3.698720, -1.986697)
PROJ.4: +proj=longlat +datum=WGS84 +no_defs +to +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs
Fehler: latitude or longitude exceeded limits

Python-Version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

**Comment by lucacasagrande** [comment]
Fixed in 973a61a59a886aed65243865f926bc04039d9b83
